version: "3"
services:
  worker:
    container_name: worker-face
    build:
      context: ../../
      dockerfile: dockers/Dockerfile
    volumes:
      - ../../secrets:/secrets      
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/others/google-service-account.json
      - DEFAULT_MYSQL_HOST=mysql-master
      - SHARDED_MYSQL_HOSTS=mysql-shard-1,mysql-shard-2
      - REDIS_HOST=redis
      - PUBSUB_EMULATOR_HOST=emulator:8085    
    entrypoint: npm run test
    depends_on:
      - mysql-master
      - mysql-shard-1
      - mysql-shard-2
      - redis    
      - emulator    
  mysql-master:
    build:
      context: ../../
      dockerfile: mocks/mysql/Dockerfile
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_ROOT_HOST=%       
  mysql-shard-1:
    build:
      context: ../../
      dockerfile: mocks/mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_ROOT_HOST=%     
    ports: 
      - 3307:3306
  mysql-shard-2:
    build:
      context: ../../
      dockerfile: mocks/mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_ROOT_HOST=%     
    ports: 
      - 3308:3306
  redis:
    image: redis
    ports:
      - 6379:6379
    entrypoint: redis-server --appendonly yes
    restart: always    
  emulator:
    image: bigtruedata/gcloud-pubsub-emulator
    ports:
      - 8085:8085
    command:
      "start --host-port 0.0.0.0:8085"

